<?php

/**
 * @file
 * Contains evolent.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function evolent_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the evolent module.
    case 'help.page.evolent':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This dispaly contact form.') . '</p>';
      return $output;

    default:
  }
}
